spring:
  application:
    name: wallet
  datasource:
    url: ${URL_JDBC}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      default_schema: wallet
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      transaction:
        jta:
          platform: enable
    show-sql: true

stripe:
  secret-key: ${STRIPE_KEY}
  endpoint-secret: ${ENDPOINT_SECRET}