spring:
  application:
    name: wallet
  datasource:
    url: ${URL_JDBC}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  stripe:
    secret-key: ${STRIPE_KEY}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      default_schema: wallet
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      transaction:
        jta:
          platform: enable
    show-sql: true
