name: Generate OpenAPI Documentation

on:
  push:
    branches:
      - main  # Cambia esto a la rama que prefieras

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Cambia a la versión que necesites

    - name: Install Axios
      run: npm install axios

    - name: Generate OpenAPI Documentation
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        node -e "
        const axios = require('axios');
        const fs = require('fs');
        async function generateDocs() {
          try {
            const response = await axios.post('https://api.openai.com/v1/engines/davinci-codex/completions', {
              prompt: 'Generate OpenAPI documentation for the following endpoints: ...', // Aquí describe tus endpoints
              max_tokens: 1500,
              temperature: 0.5,
            }, {
              headers: {
                'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
                'Content-Type': 'application/json'
              }
            });
            fs.writeFileSync('openapi.yaml', response.data.choices[0].text);
            console.log('OpenAPI documentation generated successfully.');
          } catch (error) {
            console.error('Error generating OpenAPI documentation:', error);
          }
        }
        generateDocs();
        "

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add openapi.yaml
        git commit -m "Update OpenAPI documentation"
        git push
